[package]
name = "leogpt"
version = "0.1.0"
edition = "2024"

[dependencies]
chrono = "0.4.43"
dotenvy = "0.15.7"
env_logger = "0.11.8"
log = "0.4.29"
poise = "0.6.1"
reqwest = { version = "0.12.27", default-features = false, features = [
    "json",
    "rustls-tls",
] }
serde = { version = "1.0.228", features = ["derive"] }
thiserror = "2.0.17"
tokio = { version = "1.49.0", features = ["full"] }
