services:
  app:
    image: ghcr.io/excoffierleonard/leogpt:latest
    restart: unless-stopped
    build:
      context: .
    environment:
      DISCORD_TOKEN: ${DISCORD_TOKEN}
      OPENROUTER_API_KEY: ${OPENROUTER_API_KEY}
      MUSIC_S3_URL: ${MUSIC_S3_URL}
      MEME_S3_URL: ${MEME_S3_URL}
      AWS_ACCESS_KEY_ID: ${AWS_ACCESS_KEY_ID}
      AWS_SECRET_ACCESS_KEY: ${AWS_SECRET_ACCESS_KEY}
