services:
  app:
    image: ghcr.io/excoffierleonard/leogpt:latest
    restart: unless-stopped
    build:
      context: .
    environment:
      DISCORD_TOKEN: ${DISCORD_TOKEN}
      OPENROUTER_API_KEY: ${OPENROUTER_API_KEY}
      OPENROUTER_MODEL: ${OPENROUTER_MODEL}
      SYSTEM_PROMPT: ${SYSTEM_PROMPT}